import { deletePurePressOfflineRecord, getPurePressOfflineRecord, listPurePressOfflineRecords, purePressOfflineKey, putPurePressOfflineRecord } from "./db";
export type OfflineSyncStatus="pending"|"syncing"|"conflict"|"failed";
export interface PurePressOfflineMutation { clientMutationId:string; projectId:string; action:string; payload:Record<string,unknown>; createdAt:string; ownerUid:string; baseVersion:number; baseUpdatedAt?:string; syncStatus:OfflineSyncStatus; lastError?:string; }
export interface SavedProductionDesk<T=unknown>{jobs:T[];lastSyncedAt:string;}
export function secureMutationId(){if(typeof crypto==="undefined"||typeof crypto.getRandomValues!=="function")throw new Error("Secure offline operation IDs are unavailable.");const bytes=new Uint8Array(18);crypto.getRandomValues(bytes);return `ppg_${Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("")}`;}
export async function isPurePressTrustedDevice(uid:string){const row=await getPurePressOfflineRecord<boolean>("meta",purePressOfflineKey(uid,"trusted-device"),uid);return row?.value===true;}
export async function setPurePressTrustedDevice(uid:string,enabled:boolean){if(!uid.trim())throw new Error("Owner identity is required before private offline storage can be enabled.");await putPurePressOfflineRecord("meta",{key:purePressOfflineKey(uid,"trusted-device"),uid,value:enabled,savedAt:Date.now()});}
export async function saveProductionDesk<T>(uid:string,jobs:T[],lastSyncedAt=new Date().toISOString()){if(!await isPurePressTrustedDevice(uid))return;await putPurePressOfflineRecord("production",{key:purePressOfflineKey(uid,"production-desk"),uid,value:{jobs,lastSyncedAt} satisfies SavedProductionDesk<T>,savedAt:Date.now()});}
export async function getSavedProductionDesk<T>(uid:string){return (await getPurePressOfflineRecord<SavedProductionDesk<T>>("production",purePressOfflineKey(uid,"production-desk"),uid))?.value;}
export async function saveProductionJob<T>(uid:string,projectId:string,value:T){if(!await isPurePressTrustedDevice(uid))return;await putPurePressOfflineRecord("orders",{key:purePressOfflineKey(uid,"job",projectId),uid,value,savedAt:Date.now()});}
export async function getSavedProductionJob<T>(uid:string,projectId:string){return (await getPurePressOfflineRecord<T>("orders",purePressOfflineKey(uid,"job",projectId),uid))?.value;}
export async function queueProductionMutation(uid:string,projectId:string,action:string,payload:Record<string,unknown>,baseVersion:number,baseUpdatedAt?:string){if(!await isPurePressTrustedDevice(uid))throw new Error("Enable private offline access on this trusted device before saving offline work.");const mutation:PurePressOfflineMutation={clientMutationId:secureMutationId(),projectId,action,payload,createdAt:new Date().toISOString(),ownerUid:uid,baseVersion,...(baseUpdatedAt?{baseUpdatedAt}:{}),syncStatus:"pending"};await putPurePressOfflineRecord("outbox",{key:purePressOfflineKey(uid,"outbox",mutation.clientMutationId),uid,value:mutation,savedAt:Date.now()});return mutation;}
export async function listProductionOutbox(uid:string){return (await listPurePressOfflineRecords<PurePressOfflineMutation>("outbox",uid)).map(x=>x.value).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));}
export async function updateOutboxMutation(uid:string,mutation:PurePressOfflineMutation){await putPurePressOfflineRecord("outbox",{key:purePressOfflineKey(uid,"outbox",mutation.clientMutationId),uid,value:mutation,savedAt:Date.now()});}
export async function removeOutboxMutation(uid:string,id:string){await deletePurePressOfflineRecord("outbox",purePressOfflineKey(uid,"outbox",id));}
export async function syncProductionOutbox(uid:string,tokenProvider:()=>Promise<string|undefined>,onAccepted?:(projectId:string,data:any)=>Promise<void>|void){if(!uid.trim()||typeof navigator!=="undefined"&&!navigator.onLine)return {synced:0,pending:(await listProductionOutbox(uid)).length};let synced=0;for(const mutation of await listProductionOutbox(uid)){if(mutation.syncStatus==="conflict")continue;const current={...mutation,syncStatus:"syncing" as const};await updateOutboxMutation(uid,current);try{const token=await tokenProvider();const response=await fetch(`/api/admin/purepress/jobs/${encodeURIComponent(mutation.projectId)}/production`,{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},credentials:"include",cache:"no-store",body:JSON.stringify({action:mutation.action,...mutation.payload,clientMutationId:mutation.clientMutationId,baseVersion:mutation.baseVersion,...(mutation.baseUpdatedAt?{expectedUpdatedAt:mutation.baseUpdatedAt}:{})})});const data=await response.json();if(response.status===409&&data.code==="operations_conflict"){await updateOutboxMutation(uid,{...mutation,syncStatus:"conflict",lastError:data.error||"This job changed while you were offline."});break;}if(!response.ok)throw new Error(data.error||"Saved update could not sync.");await removeOutboxMutation(uid,mutation.clientMutationId);synced++;await onAccepted?.(mutation.projectId,data);}catch(reason){await updateOutboxMutation(uid,{...mutation,syncStatus:"failed",lastError:reason instanceof Error?reason.message:"Saved update could not sync."});break;}}
return {synced,pending:(await listProductionOutbox(uid)).length};}
