const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const pkg = JSON.parse(read('package.json'));
const browserPush = read('src/components/BrowserPushControl.tsx');
const communications = read('src/lib/boardsignal/server/communications.ts');
const delivery = read('src/lib/boardsignal/delivery.ts');
const serverDelivery = read('src/lib/boardsignal/server/delivery.ts');
const email = read('src/lib/boardsignal/server/email.ts');
const adminRoute = read('src/app/api/admin/boardsignal/communications/route.ts');
const founderUi = read('src/components/FounderCommunications.tsx');
const newsroom = read('src/components/FounderNewsroomSummary.tsx');
const profile = read('src/components/PlayerProfileNotifications.tsx');
const room = read('src/components/BoardSignalPlayerRoom.tsx');
const header = read('src/components/Header.tsx');
const adminLayout = read('src/app/admin/layout.tsx');
const marker = read('src/components/FounderDeviceMarker.tsx');
const middleware = read('middleware.ts');
const sw = read('public/sw.js');
const manifest = read('src/app/manifest.ts');
const installPrompt = read('src/components/InstallPrompt.tsx');
const guide = read('src/lib/boardsignal/guide.ts');
const firestore = read('firestore.rules');
const fidDoc = read('docs/BOARDSIGNAL_FCM_FID_MIGRATION.md');

function pngSize(rel) {
  const buf = fs.readFileSync(path.join(root, rel));
  assert.equal(buf.subarray(1,4).toString(), 'PNG');
  return [buf.readUInt32BE(16), buf.readUInt32BE(20)];
}

test('01 exact baseline continuity/PWA scripts remain present', () => { assert.match(pkg.scripts['test:ask'], /boardsignal-ask-board-signal/); assert.equal(pkg.scripts['test:pwa'], 'node --test tests/boardsignal-pwa-offline.test.cjs'); });
test('02 current prebuild remains unchanged', () => assert.equal(pkg.scripts.prebuild, 'npm run prepare:stockfish && npm run test:contrast'));
test('03 delivery tests are artifact QA only', () => { assert.equal(pkg.scripts['test:delivery'], 'node --test tests/boardsignal-delivery-polish.test.cjs'); assert.doesNotMatch(pkg.scripts.prebuild, /delivery|pwa/); });
test('04 push permission is requested only inside explicit enable flow', () => { assert.equal((browserPush.match(/await Notification\.requestPermission\(\)/g)||[]).length, 1); assert.match(browserPush, /async function enable\(\)[\s\S]*const nextPermission = await Notification\.requestPermission/); });
test('05 missing VAPID preserves Inbox message', () => assert.match(browserPush, /Browser alerts not configured yet[\s\S]*In-app Inbox still works/));
test('06 configured push uses existing service worker readiness', () => assert.match(browserPush, /navigator\.serviceWorker\.ready/));
test('07 current token registration path remains getToken', () => assert.match(browserPush, /client\.getToken/));
test('08 no half FID registration is introduced', () => { assert.doesNotMatch(browserPush, /onRegistered|onUnregistered|client\.register/); assert.match(fidDoc, /Do not create a half-token \/ half-FID path/i); });
test('09 only one service worker registration remains', () => { const sources = fs.readdirSync(path.join(root,'src/components')).filter(f=>f.endsWith('.tsx')).map(f=>read('src/components/'+f)).join('\n'); assert.equal((sources.match(/serviceWorker\.register\(/g)||[]).length,1); });
test('10 Desk Ready deep links to Desk', () => assert.match(delivery, /case "desk_ready"[\s\S]*tab=desk/));
test('11 friend events deep link to Friends', () => assert.match(delivery, /case "friend_request"[\s\S]*case "friend_accepted"[\s\S]*tab=friends/));
test('12 founder/private custom links to Inbox', () => assert.match(delivery, /case "custom"[\s\S]*tab=inbox/));
test('13 push denial is respected without retry prompt', () => assert.match(browserPush, /permission === "denied"[\s\S]*will not ask again here/));
test('14 push eligibility checks browser preference', () => assert.match(communications, /notificationPreferences\?\.browserPush/));
test('15 founder push test lives on existing admin route', () => { assert.match(adminRoute,/testPush/); assert.match(adminRoute,/sendFounderTestBrowserAlert/); });
test('16 founder push test targets active BoardSignal player only', () => assert.match(communications, /sendFounderTestBrowserAlert[\s\S]*role !== "player"[\s\S]*accessStatus !== "active"/));
test('17 test push reports not eligible instead of fake success', () => assert.match(communications,/status: "not_eligible"/));
test('18 email provider adapter is server only', () => assert.match(email,/^import "server-only";/));
test('19 email provider uses server RESEND_API_KEY', () => { assert.match(email,/process\.env\.RESEND_API_KEY/); assert.doesNotMatch(email,/NEXT_PUBLIC_RESEND/); });
test('20 missing Resend config fails gracefully', () => assert.match(email,/configured: false, delivered: false/));
test('21 email consent is required', () => assert.match(delivery,/betaContactConsent !== true/));
test('22 valid email is required', () => assert.match(delivery,/isValidBoardSignalEmail\(account\.preferredContactValue\)/));
test('23 Discord and Telegram contact methods cannot be emailed', () => assert.match(delivery,/preferredContactMethod !== "email"/));
test('24 email notification preference is respected', () => assert.match(delivery,/notificationPreferences\?\.email !== true/));
test('25 founder preview returns email eligibility', () => assert.match(communications,/emailEligibleCount/));
test('26 delivery result distinguishes inbox push email', () => { assert.match(founderUi,/In-app sent:/); assert.match(founderUi,/Push delivered:/); assert.match(founderUi,/Email delivered:/); });
test('27 newsroom has deterministic delivery status', () => { assert.match(newsroom,/DELIVERY STATUS/); assert.match(newsroom,/Browser Push/); assert.match(newsroom,/Email/); });
test('28 admin remains protected by Basic Auth middleware', () => { assert.match(middleware,/ADMIN_PASSWORD/); assert.match(middleware,/\/admin/); });
test('29 admin remains network-only in service worker', () => assert.match(sw,/url\.pathname\.startsWith\("\/admin"\)/));
test('30 founder local device marker is not authorization', () => { assert.match(marker,/convenience only/); assert.match(marker,/never authorizes \/admin/); assert.match(adminLayout,/FounderDeviceMarker/); });
test('31 ordinary player does not see founder entry without marker', () => { assert.match(header,/founderEntry \?/); assert.match(header,/BOARDSIGNAL_FOUNDER_DEVICE_KEY/); });
test('32 founder entry is restricted to standalone mode', () => assert.match(header,/isStandaloneBoardSignal\(\) &&/));
test('33 app badge is feature detected', () => assert.match(read('src/lib/boardsignal/offline/badge.ts'),/typeof badgeNavigator\.setAppBadge === "function"/));
test('34 app badge sync uses unread Inbox count', () => assert.match(room,/syncBoardSignalAppBadge\(unreadCount\)/));
test('35 badge clears on sign out/account switch', () => { assert.ok((room.match(/clearBoardSignalAppBadge/g)||[]).length >= 3); });
test('36 manifest contains narrow and wide screenshots', () => { assert.match(manifest,/screenshots:/); assert.match(manifest,/form_factor: "narrow"/); assert.match(manifest,/form_factor: "wide"/); });
test('37 mobile player-room screenshot exists with declared size', () => assert.deepEqual(pngSize('public/pwa/boardsignal-player-room-mobile.png'),[1080,1920]));
test('38 mobile Universe screenshot exists with declared size', () => assert.deepEqual(pngSize('public/pwa/boardsignal-universe-mobile.png'),[1080,1920]));
test('39 wide player-room screenshot exists with declared size', () => assert.deepEqual(pngSize('public/pwa/boardsignal-player-room-wide.png'),[1440,900]));
test('40 wide Universe screenshot exists with declared size', () => assert.deepEqual(pngSize('public/pwa/boardsignal-universe-wide.png'),[1440,900]));
test('41 richer install keeps engagement-aware timing', () => { assert.match(installPrompt,/installDismissedRecently/); assert.match(installPrompt,/PWA_ENGAGED/); });
test('42 service worker PWA v4 architecture remains intact', () => { assert.match(sw,/boardsignal-shell-\$\{CACHE_VERSION\}/); assert.match(sw,/CACHE_VERSION = "v4"/); });
test('43 existing push handler survives', () => assert.match(sw,/addEventListener\("push"/));
test('44 existing notificationclick survives', () => assert.match(sw,/addEventListener\("notificationclick"/));
test('45 Ask explains missing browser configuration', () => assert.match(guide,/Browser alerts haven't been configured by BoardSignal yet/));
test('46 Ask explains missing email provider', () => assert.match(guide,/Email delivery isn't active yet/));
test('47 Ask explains installed app badge', () => assert.match(guide,/number on an installed BoardSignal icon represents unread Inbox messages/));
test('48 profile email toggle requires email contact and consent', () => { assert.match(profile,/emailContactReady/); assert.match(profile,/EMAIL ALERTS/); });
test('49 server readiness exposes no secret values', () => { assert.match(serverDelivery,/browserPushConfigured/); assert.match(serverDelivery,/emailConfigured/); assert.doesNotMatch(serverDelivery,/apiKey:/); });
test('50 no Firestore delivery collection is introduced', () => { assert.doesNotMatch(firestore,/deliveryStatus|resend|emailDelivery/); });
test('51 Firebase versions are not upgraded', () => { assert.equal(pkg.dependencies.firebase,'^11.9.0'); assert.equal(pkg.dependencies['firebase-admin'],'^13.4.0'); });
test('52 no Resend package dependency is added', () => assert.equal(pkg.dependencies.resend, undefined));
test('53 FID maintenance note records current dependency boundary', () => { assert.match(fidDoc,/firebase` `\^11\.9\.0/); assert.match(fidDoc,/firebase-admin` `\^13\.4\.0/); assert.match(fidDoc,/12\.14\.0/); assert.match(fidDoc,/14\.1\.0/); });
test('54 FID maintenance note records Node 22 implication', () => assert.match(fidDoc,/Node\.js 22/));
test('55 configuration env contract stays minimal', () => { const all=[serverDelivery,email].join('\n'); assert.match(all,/NEXT_PUBLIC_FIREBASE_VAPID_KEY/); assert.match(all,/RESEND_API_KEY/); assert.match(all,/BOARDSIGNAL_EMAIL_FROM/); assert.match(all,/BOARDSIGNAL_EMAIL_REPLY_TO/); });
