const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const root=path.resolve(__dirname,".."),read=p=>fs.readFileSync(path.join(root,p),"utf8"),dist=p=>require(path.join(root,".test-dist-purepress-h1",p));
const L=dist("src/lib/purepress/i18n/locales.js"),I=dist("src/lib/purepress/i18n/index.js"),P=dist("src/lib/purepress/customerProjection.js");
const EN=dist("src/lib/purepress/i18n/catalog.en.js").PUREPRESS_EN_CATALOG,TN=dist("src/lib/purepress/i18n/catalog.tn-BW.js").PUREPRESS_TN_BW_CATALOG;
const provider=read("src/components/purepress/PurePressLanguageProvider.tsx"),layout=read("src/app/layout.tsx"),customer=read("src/components/purepress/PurePressCustomerPortal.tsx"),offline=read("src/components/purepress/PurePressCustomerOffline.tsx"),server=read("src/lib/purepress/server/customerPortal.ts"),pkg=JSON.parse(read("package.json"));
test("exact locales",()=>assert.deepEqual(L.PUREPRESS_LOCALES,["en-BW","tn-BW"]));
for(const x of ["tn","tn-BW","tn-ZA"])test(`normalize ${x}`,()=>assert.equal(L.normalizePurePressLocale(x),"tn-BW"));
for(const x of ["en","en-BW","en-US"])test(`normalize ${x}`,()=>assert.equal(L.normalizePurePressLocale(x),"en-BW"));
test("reject unknown",()=>assert.equal(L.normalizePurePressLocale("fr"),null));
test("priority explicit",()=>assert.equal(L.resolvePurePressLocale({explicit:"en",stored:"tn",url:"tn",browser:["tn"]}),"en-BW"));
test("priority stored",()=>assert.equal(L.resolvePurePressLocale({stored:"en",url:"tn",browser:["tn"]}),"en-BW"));
test("priority URL",()=>assert.equal(L.resolvePurePressLocale({url:"tn",browser:["en"]}),"tn-BW"));
test("browser Setswana",()=>assert.equal(L.resolvePurePressLocale({browser:["en-US","tn-BW"]}),"tn-BW"));
test("English default",()=>assert.equal(L.resolvePurePressLocale({browser:["en-US"]}),"en-BW"));
test("locale-only storage key",()=>{assert.equal(L.PUREPRESS_LOCALE_STORAGE_KEY,"purepress:locale:v1");assert.doesNotMatch(L.PUREPRESS_LOCALE_STORAGE_KEY,/uid|email|token|order/i)});
test("route scope PurePress",()=>["/","/services","/request-a-quote","/my-purepress","/admin","/admin/login","/proof/x","/quote/x","/offline/purepress-studio"].forEach(r=>assert.equal(L.isPurePressLocaleSurface(r),true,r)));
test("route scope excludes BoardSignal",()=>["/boardsignal","/boardsignal/player-room","/admin/players"].forEach(r=>assert.equal(L.isPurePressLocaleSurface(r),false,r)));
test("catalog parity",()=>assert.deepEqual(Object.keys(EN).sort(),Object.keys(TN).sort()));
test("catalog substantial",()=>assert.ok(Object.keys(EN).length>=300,Object.keys(EN).length));
test("no empty catalog",()=>{for(const [k,v] of Object.entries(EN))assert.ok(String(v).trim(),k);for(const [k,v] of Object.entries(TN))assert.ok(String(v).trim(),k)});
test("placeholder parity",()=>{for(const k of Object.keys(EN))assert.deepEqual(I.purePressPlaceholderNames(EN[k]),I.purePressPlaceholderNames(TN[k]),k)});
test("no catalog HTML injection path",()=>assert.doesNotMatch(provider, /catalog.*dangerouslySetInnerHTML/));
test("12 semantic codes",()=>assert.deepEqual(P.PUREPRESS_CUSTOMER_STATUS_CODES,["REQUEST_RECEIVED","NEEDS_INFORMATION","QUOTE_BEING_PREPARED","QUOTE_READY","ARTWORK_BEING_PREPARED","ARTWORK_READY","READY_FOR_PRODUCTION","IN_PRODUCTION","QUALITY_CHECK","READY_FOR_COLLECTION","COMPLETED","CANCELLED"]));
const cases={new_request:"REQUEST_RECEIVED",needs_information:"NEEDS_INFORMATION",quote_ready:"QUOTE_BEING_PREPARED",awaiting_quote_approval:"QUOTE_READY",artwork_proof:"ARTWORK_BEING_PREPARED",awaiting_proof_approval:"ARTWORK_READY",approved_for_production:"READY_FOR_PRODUCTION",in_production:"IN_PRODUCTION",quality_check:"QUALITY_CHECK",ready:"READY_FOR_COLLECTION",completed:"COMPLETED",cancelled:"CANCELLED"};
for(const [s,c] of Object.entries(cases))test(`${s} semantic`,()=>{const r=P.projectPurePressCustomerStatusSemantic(s);assert.equal(r.code,c);assert.match(r.headlineKey,/^customer\.status\./)});
test("legacy H status remains deterministic",()=>assert.equal(P.projectPurePressCustomerStatus("in_production").headline,"We’re making your order."));
test("server emits semantic status",()=>assert.match(server,/projectPurePressCustomerStatusSemantic\(job\.status\)/));
test("server quote proof labels are keys",()=>{assert.match(server,/labelKey:/);assert.doesNotMatch(server,/label: "QUOTE BEING PREPARED"/)});
test("customer UI renders semantic keys",()=>{assert.match(customer,/t\(order\.status\.headlineKey\)/);assert.match(customer,/t\(order\.status\.nextKey\)/);assert.match(customer,/t\(order\.status\.explanationKey\)/)});
test("offline UI renders same semantic keys",()=>{assert.match(offline,/t\(order\.status\.headlineKey\)/);assert.match(offline,/t\(order\.status\.nextKey\)/)});
test("human text has no-translate boundaries",()=>assert.match(customer+read("src/components/purepress/PurePressQuoteApproval.tsx")+read("src/components/purepress/PurePressProofApproval.tsx"),/data-pp-no-translate/));
test("shared provider mounted once",()=>assert.match(layout,/<PurePressLanguageProvider>/));
test("document lang changes",()=>assert.match(provider,/document\.documentElement\.lang=locale/));
test("root defaults en-BW",()=>assert.match(layout,/lang="en-BW"/));
test("early bootstrap",()=>{assert.match(layout,/purePressLocaleBootstrap/);assert.match(layout,/purepress:locale:v1/);assert.match(layout,/navigator\.languages/)});
test("no routine TN English paint",()=>assert.match(layout,/ppLocaleReady/));
test("fixed text observer",()=>{assert.match(provider,/MutationObserver/);assert.match(provider,/aria-label/);assert.match(provider,/placeholder/)});
test("switch is accessible",()=>{const s=read("src/components/purepress/PurePressLanguageSwitch.tsx"),css=read("src/components/purepress/PurePressLanguageSwitch.module.css");assert.match(s,/English/);assert.match(s,/Setswana/);assert.match(s,/aria-pressed/);assert.match(css,/min-height:44px/);assert.match(css,/:focus-visible/)});
test("locale aware customer formatting",()=>{assert.match(customer,/formatPurePressMoney\(locale/);assert.match(customer,/formatPurePressDate\(locale/);assert.match(customer,/formatPurePressDateTime\(locale/)});
test("secure quote locale money",()=>assert.match(read("src/components/purepress/PurePressQuoteApproval.tsx"),/formatPurePressMoney\(locale/));
test("secure proof locale time",()=>assert.match(read("src/components/purepress/PurePressProofApproval.tsx"),/formatPurePressDateTime\(locale/));
test("Africa Gaborone formatter",()=>assert.match(read("src/lib/purepress/i18n/format.ts"),/Africa\/Gaborone/));
for(const text of ["Home","Services","Our Work","Request a Quote","What are you branding?","Tell us what you’re branding.","INSTALL PUREPRESS","NOT NOW","YOUR ORDERS","KEEP MY ORDERS ON THIS DEVICE","APPROVE QUOTE","APPROVE ARTWORK","PUREPRESS STUDIO","PRODUCTION DESK","GARMENTS / RECEIVING","READY FOR PRODUCTION","QUALITY CHECK","START PRODUCTION","FINISH PRODUCTION"])test(`catalog covers ${text}`,()=>assert.ok(I.purePressCatalogKeyForEnglishText(text),text));
test("no Google runtime",()=>assert.doesNotMatch(provider+read("src/lib/purepress/i18n/index.ts"),/translate\.google|googleapis|cloudtranslation|GOOGLE_API_KEY/i));
test("no translation dependency",()=>Object.keys({...pkg.dependencies,...pkg.devDependencies}).forEach(n=>assert.doesNotMatch(n,/i18n|translate|intl-message/i)));
test("prebuild H1 position",()=>{const b=pkg.scripts.prebuild;assert.ok(b.indexOf("test:purepress-patch-h")<b.indexOf("test:purepress-patch-h1"));assert.ok(b.indexOf("test:purepress-patch-h1")<b.indexOf("test:critical"));assert.ok(b.indexOf("test:purepress-patch-h1")<b.indexOf("test:pwa"))});
test("dependency versions unchanged",()=>{assert.equal(pkg.dependencies.firebase,"^11.9.0");assert.equal(pkg.dependencies["firebase-admin"],"^13.4.0");assert.equal(pkg.dependencies.next,"^15.5.15");assert.equal(pkg.dependencies.react,"^19.2.3")});
test("single service worker",()=>assert.deepEqual(fs.readdirSync(path.join(root,"public")).filter(n=>/^sw.*\.js$/i.test(n)),["sw.js"]));
