const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ROOT=process.cwd();const read=(p)=>fs.readFileSync(path.join(ROOT,p),'utf8');
const cases=[
['quote artwork remains private',()=>{assert.ok(read('src/app/api/uploadthing/core.ts').includes('acl: "private"'))}],
['order asset route has private ACL',()=>{assert.ok(read('src/app/api/uploadthing/core.ts').includes('blob: { maxFileSize: "16MB", maxFileCount: 1, acl: "private" }'))}],
['upload completion writes durable metadata',()=>{assert.ok(read('src/app/api/uploadthing/core.ts').includes('recordPurePressJobFileUpload'))}],
['job file visibility is internal',()=>{assert.ok(read('src/lib/purepress/server/jobFiles.ts').includes('visibility: "internal"'))}],
['signed URL TTL is five minutes',()=>{assert.ok(read('src/lib/purepress/server/jobFiles.ts').includes('"5 minutes"'))}],
['durable file record never stores viewUrl',()=>{assert.ok(!read('src/lib/purepress/server/jobFiles.ts').includes('viewUrl: signed.ufsUrl, uploadedBy'))}],
['proof route disables caching',()=>{assert.ok(read('src/app/api/purepress/proof/[token]/route.ts').includes('no-store, private'))}],
['proof route disables indexing',()=>{assert.ok(read('src/app/api/purepress/proof/[token]/route.ts').includes('X-Robots-Tag'))}],
['proof page metadata disables indexing',()=>{assert.ok(read('src/app/proof/[token]/page.tsx').includes('noarchive: true'))}],
['admin route requires PurePress admin',()=>{assert.ok(read('src/app/api/admin/purepress/jobs/[projectId]/artwork-proof/route.ts').includes('requirePurePressAdmin'))}],
['admin client sends Firebase bearer token',()=>{assert.ok(read('src/components/purepress/PurePressArtworkProofPanel.tsx').includes('Authorization'))}],
['production files are admin only',()=>{assert.ok(read('src/lib/purepress/uploads.ts').includes('roles:["admin"]'))}],
['customer artwork permits customer and admin',()=>{assert.ok(read('src/lib/purepress/uploads.ts').includes('roles:["customer","admin"]'))}],
['all upload policy type requires nonpublic default',()=>{assert.ok(read('src/lib/purepress/uploads.ts').includes('publicByDefault: false'))}],
['production category is distinct',()=>{assert.ok(read('src/lib/purepress/uploads.ts').includes('digitized_production_file'))}],
['sample category is distinct',()=>{assert.ok(read('src/lib/purepress/uploads.ts').includes('sample_evidence'))}],
['quote artwork category is preserved',()=>{assert.ok(read('src/lib/purepress/uploads.ts').includes('quote_artwork'))}],
['upload authorization validates operational job',()=>{assert.ok(read('src/lib/purepress/server/uploadAuthorization.ts').includes('assertOperationalJob'))}],
['customer access checks order ownership',()=>{assert.ok(read('src/lib/purepress/server/uploadAuthorization.ts').includes('purePressCustomerCanAccessJob'))}],
['admin-only category rejection exists',()=>{assert.ok(read('src/lib/purepress/server/uploadAuthorization.ts').includes('admin-only'))}],
['customer proof page states exact revision approval',()=>{assert.ok(read('src/components/purepress/PurePressProofApproval.tsx').includes('exact proof revision'))}],
['customer can approve',()=>{assert.ok(read('src/components/purepress/PurePressProofApproval.tsx').includes('APPROVE PROOF'))}],
['customer can request changes',()=>{assert.ok(read('src/components/purepress/PurePressProofApproval.tsx').includes('REQUEST CHANGES'))}],
['request changes comment is required',()=>{assert.ok(read('src/components/purepress/PurePressProofApproval.tsx').includes('name="comment" required'))}],
['owner can replace approval link',()=>{assert.ok(read('src/components/purepress/PurePressArtworkProofPanel.tsx').includes('REPLACE APPROVAL LINK'))}],
['owner can record approval',()=>{assert.ok(read('src/components/purepress/PurePressArtworkProofPanel.tsx').includes('RECORD OWNER APPROVAL'))}],
['owner final action names approved for production',()=>{assert.ok(read('src/components/purepress/PurePressArtworkProofPanel.tsx').includes('MARK APPROVED FOR PRODUCTION'))}],
['UI explains quote artwork no relabel',()=>{assert.ok(read('src/components/purepress/PurePressArtworkProofPanel.tsx').includes('never relabelled'))}],
['proof links open safely',()=>{assert.ok(read('src/components/purepress/PurePressProofApproval.tsx').includes('rel="noreferrer"'))}],
['admin API has body limit',()=>{assert.ok(read('src/app/api/admin/purepress/jobs/[projectId]/artwork-proof/route.ts').includes('MAX_BODY_BYTES'))}],
['public decision API has body limit',()=>{assert.ok(read('src/app/api/purepress/proof/[token]/route.ts').includes('8*1024'))}],
['no public media automation in upload core',()=>{assert.ok(!read('src/app/api/uploadthing/core.ts').includes('PublicWorkMedia'))}],
['no Firebase deployment command',()=>{assert.ok(!read('package.json').includes('firebase deploy'))}],
['no Vercel deployment command',()=>{assert.ok(!read('package.json').includes('vercel deploy'))}],
['dependencies remain baseline set',()=>{assert.deepEqual(Object.keys(JSON.parse(read('package.json')).dependencies).sort(),['@uploadthing/react','@vercel/analytics','@vercel/speed-insights','chess.js','firebase','firebase-admin','jspdf','lucide-react','next','react','react-dom','stockfish','uploadthing'].sort())}],
['Firestore rules retain the protected PurePress boundaries',()=>{const rules=read('firestore.rules');assert.ok(rules.includes('match /purepressQuoteRequests/{requestId}'));assert.ok(rules.includes('match /projects/{projectId}'));assert.ok(rules.includes('allow read, create, update, delete: if isPurePressAdmin();'))}]
];for(const [name,fn] of cases)test(name,fn);
