const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ROOT=process.cwd();const read=(p)=>fs.readFileSync(path.join(ROOT,p),'utf8');
const cases=[
['final gate helper exists',()=>{assert.ok(read('src/lib/purepress/artworkProof.ts').includes('canFinalizeArtwork'))}],
['requires production ready artwork',()=>{assert.ok(read('src/lib/purepress/artworkProof.ts').includes('readiness.artwork !== "production_ready"'))}],
['requires private artwork source',()=>{assert.ok(read('src/lib/purepress/artworkProof.ts').includes('At least one private customer or quote artwork source is required.'))}],
['requires approved current proof',()=>{assert.ok(read('src/lib/purepress/artworkProof.ts').includes('proofState.status !== "approved"'))}],
['requires proof readiness approved',()=>{assert.ok(read('src/lib/purepress/artworkProof.ts').includes('readiness.proof !== "approved"'))}],
['checks digitising required',()=>{assert.ok(read('src/lib/purepress/artworkProof.ts').includes('digitizingRequired'))}],
['checks digitising complete',()=>{assert.ok(read('src/lib/purepress/artworkProof.ts').includes('digitizingStatus !== "complete"'))}],
['checks production file refs',()=>{assert.ok(read('src/lib/purepress/artworkProof.ts').includes('productionFileRefs'))}],
['checks sample required',()=>{assert.ok(read('src/lib/purepress/artworkProof.ts').includes('sampleRequired'))}],
['checks sample approved',()=>{assert.ok(read('src/lib/purepress/artworkProof.ts').includes('readiness.sample !== "approved"'))}],
['finalize action exists',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('finalize_for_production'))}],
['final status is approved for production',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('approved_for_production'))}],
['production remains not ready',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('readiness.production":"not_ready'))}],
['artwork readiness action exists',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('set_artwork_readiness'))}],
['digitising action exists',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('set_digitising'))}],
['embroidery facts action exists',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('set_embroidery_facts'))}],
['sample readiness action exists',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('set_sample_readiness'))}],
['artwork states include received',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('"received"'))}],
['artwork states include cleanup',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('needs_cleanup'))}],
['artwork states include digitizing',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('digitizing'))}],
['artwork states include production ready',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('production_ready'))}],
['digitising states include in progress',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('in_progress'))}],
['digitising completion stamps date',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('digitizedAt'))}],
['digitising completion stamps actor',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('digitizedBy'))}],
['stitch count is optional',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('delete embroidery.stitchCount'))}],
['thread colours are optional',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('delete embroidery.threadColorRefs'))}],
['sample required flag is recorded',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('sampleRequired'))}],
['customer artwork ids are durable',()=>{assert.ok(read('src/lib/purepress/server/jobFiles.ts').includes('customerArtworkFileIds'))}],
['production file ids are durable',()=>{assert.ok(read('src/lib/purepress/server/jobFiles.ts').includes('productionFileIds'))}],
['production refs use existing embroidery spec',()=>{assert.ok(read('src/lib/purepress/server/jobFiles.ts').includes('embroidery.productionFileRefs'))}],
['sample evidence ids are durable',()=>{assert.ok(read('src/lib/purepress/server/jobFiles.ts').includes('sampleEvidenceFileIds'))}],
['bundle exposes quote artwork ids',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('sourceQuoteArtworkFileIds'))}],
['bundle includes quote artwork category',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('"quote_artwork"'))}],
['workflow final action names scope boundary',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('outside Patch F'))}],
['final gate explains sample blocker',()=>{assert.ok(read('src/lib/purepress/artworkProof.ts').includes('required sew-out/sample'))}],
['all nonfinal workflow mutations reset production',()=>{assert.ok(read('src/lib/purepress/server/artworkWorkflow.ts').includes('readiness.production="not_ready"'))}],
['Patch F never assigns in_production',()=>{assert.ok(!read('src/lib/purepress/server/artworkWorkflow.ts').includes('purepress.status:"in_production"'))}]
];for(const [name,fn] of cases)test(name,fn);
