const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');const panel=read('src/components/purepress/PurePressProductionPanel.tsx'),desk=read('src/components/purepress/PurePressProductionDesk.tsx'),offline=read('src/components/purepress/PurePressOfflineStudioView.tsx'),pkg=JSON.parse(read('package.json')),firestore=fs.existsSync(path.join(root,'firestore.rules'))?read('firestore.rules'):'';
test('production floor exposes receiving machine progress qc next action',()=>{for(const s of ['GARMENTS / RECEIVING','PRODUCTION PLAN','PROGRESS','QUALITY CHECK','NEXT ACTION'])assert.match(panel,new RegExp(s))});
test('studio exposes operational desk groupings',()=>{for(const s of ['ATTENTION','WAITING','READY FOR PRODUCTION','SCHEDULED','IN PRODUCTION','QC','READY','ALL ACTIVE'])assert.match(desk,new RegExp(s))});
test('offline state is clearly labelled saved not live',()=>{assert.match(desk,/OFFLINE — SHOWING SAVED PUREPRESS DATA/);assert.match(offline,/OFFLINE — SHOWING SAVED PUREPRESS DATA/);assert.match(panel,/WAITING TO SYNC|waiting to sync/i)});
test('trusted device wording discloses private retention',()=>{assert.match(desk,/KEEP ACTIVE JOBS ON THIS DEVICE/);assert.match(desk,/trusted device retains private job metadata/)});
test('offline lifecycle intent is explicitly non-authoritative',()=>assert.match(panel,/stage shown above remains the last authoritative saved stage/i));
test('Patch G test is permanent prebuild gate after F',()=>{assert.ok(pkg.scripts['test:purepress-patch-g']);assert.match(pkg.scripts.prebuild,/test:purepress-patch-f && npm run test:purepress-patch-g && npm run test:critical/)});
test('no dependency versions changed by Patch G tests',()=>{assert.equal(pkg.dependencies.firebase,'^11.9.0');assert.equal(pkg.dependencies['firebase-admin'],'^13.4.0');assert.equal(pkg.dependencies.uploadthing,'^7.7.4')});
test('firestore rules are not part of implementation expectation',()=>{if(firestore)assert.ok(firestore.length>0)});
