const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ROOT=process.cwd();const read=(p)=>fs.readFileSync(path.join(ROOT,p),'utf8');
const s=read('src/lib/purepress/server/proofs.ts');const cases=[
['proof collection is separate',()=>assert.ok(s.includes('PUREPRESS_PROOFS_COLLECTION'))],
['proof state collection is separate',()=>assert.ok(s.includes('PUREPRESS_PROOF_STATES_COLLECTION'))],
['proof access collection is separate',()=>assert.ok(s.includes('PUREPRESS_PROOF_ACCESS_COLLECTION'))],
['token uses random bytes',()=>assert.ok(s.includes('randomBytes(32)'))],
['token is base64url',()=>assert.ok(s.includes('base64url'))],
['token is SHA-256 hashed',()=>assert.ok(s.includes('createHash("sha256")'))],
['proof revision uses transaction create',()=>assert.ok(s.includes('transaction.create(proofRef,proof)'))],
['proof state uses transaction create',()=>assert.ok(s.includes('transaction.create(stateRef,state)'))],
['access record uses transaction create',()=>assert.ok(s.includes('transaction.create(accessRef'))],
['revision increments',()=>assert.ok(s.includes('currentProofRevision??0)+1'))],
['history pointer appends',()=>assert.ok(s.includes('proofRevisionIds'))],
['current proof pointer updates',()=>assert.ok(s.includes('workflow.currentProofId=proof.id'))],
['current proof revision updates',()=>assert.ok(s.includes('workflow.currentProofRevision=revision'))],
['issue moves lifecycle to awaiting proof',()=>assert.ok(s.includes('awaiting_proof_approval'))],
['issue sets proof awaiting customer',()=>assert.ok(s.includes('awaiting_customer'))],
['issue keeps production not ready',()=>assert.ok(s.includes('readiness.production":"not_ready'))],
['replacement invalidates old link',()=>assert.ok(s.includes('active:false,replacedAt'))],
['replacement creates new access record',()=>assert.ok(s.includes('replacement:true'))],
['replacement only while awaiting',()=>assert.ok(s.includes('Only an awaiting-customer proof'))],
['public token lookup uses hash document',()=>assert.ok(s.includes('doc(hash)'))],
['public view validates active token',()=>assert.ok(s.includes('active!==true'))],
['public view verifies current hash',()=>assert.ok(s.includes('state.activeTokenHash!==resolved.hash'))],
['proof files get signed URLs',()=>assert.ok(s.includes('createPrivateJobFileViewUrl'))],
['customer decision uses secure_link',()=>assert.ok(s.includes('"secure_link"'))],
['owner decision uses owner_recorded',()=>assert.ok(s.includes('"owner_recorded"'))],
['customer decision records decision time',()=>assert.ok(s.includes('decisionRecordedAt'))],
['decision keeps hashed link readable',()=>assert.ok(s.includes('status:decision.type,decision,updatedAt'))],
['approved proof does not start production',()=>assert.ok(s.includes('purepress.status":"artwork_proof'))],
['changes request routes back to artwork proof',()=>assert.ok(s.includes('Prepare a revised artwork proof'))],
['only current proof can be decided',()=>assert.ok(s.includes('Only the current awaiting proof can be decided'))],
['owner cannot overwrite decided proof',()=>assert.ok(s.includes('This proof already has a decision'))],
['history is revision sorted',()=>assert.ok(s.includes('sort((a,b)=>b.revision-a.revision)'))],
['proof revision captures placement',()=>assert.ok(s.includes('placementSummary'))],
['proof revision captures design width',()=>assert.ok(s.includes('designWidthMm'))],
['proof revision captures design height',()=>assert.ok(s.includes('designHeightMm'))],
['proof revision captures thread summary',()=>assert.ok(s.includes('threadColorSummary'))]
];for(const [name,fn] of cases)test(name,fn);
