"use client";
import { type FormEvent, useCallback, useEffect, useState } from "react";
import { auth } from "@/utils/firebaseConfig";
import { getSavedProductionJob, isPurePressTrustedDevice, listProductionOutbox, queueProductionMutation, saveProductionJob, secureMutationId, syncProductionOutbox } from "@/lib/purepress/offline/production";
import styles from "./PurePressProductionPanel.module.css";
type Detail={projectId:string;referenceCode:string;status:string;operationsVersion:number;quantity:number|null;supplySource:string;readiness:any;receiving:any[];productionPlan:any;qualityChecks:any[];nextAction:any;history:any[];updatedAt:string};
const friendly=(v?:string)=>v?v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase()):"—";
async function token(){return auth.currentUser?.getIdToken();}
export default function PurePressProductionPanel({projectId}:{projectId:string}){
 const [detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(""),[saved,setSaved]=useState(false),[pending,setPending]=useState(0),[offline,setOffline]=useState(typeof navigator!=="undefined"&&!navigator.onLine);
 const refreshPending=useCallback(async()=>{const uid=auth.currentUser?.uid;if(uid)setPending((await listProductionOutbox(uid)).filter(x=>x.projectId===projectId).length);},[projectId]);
 const load=useCallback(async()=>{const uid=auth.currentUser?.uid;setError("");try{const t=await token();const response=await fetch(`/api/admin/purepress/jobs/${encodeURIComponent(projectId)}/production`,{headers:t?{Authorization:`Bearer ${t}`}:{},credentials:"include",cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not load production operations.");setDetail(data);setOffline(false);if(uid&&await isPurePressTrustedDevice(uid)){await saveProductionJob(uid,projectId,data);setSaved(true);}}catch(reason){setOffline(true);if(uid){const cached=await getSavedProductionJob<Detail>(uid,projectId);if(cached){setDetail(cached);setSaved(true);}else setError(reason instanceof Error?reason.message:"Production operations unavailable.");}else setError("Connect once with the owner account before private offline job data can be opened.");}finally{await refreshPending();}},[projectId,refreshPending]);
 useEffect(()=>{void load();const online=()=>{setOffline(false);void syncNow();};const off=()=>setOffline(true);const focus=()=>{if(navigator.onLine)void syncNow();};window.addEventListener("online",online);window.addEventListener("offline",off);window.addEventListener("focus",focus);return()=>{window.removeEventListener("online",online);window.removeEventListener("offline",off);window.removeEventListener("focus",focus);};},[load]);
 async function syncNow(){const uid=auth.currentUser?.uid;if(!uid||!navigator.onLine)return;await syncProductionOutbox(uid,token,async(id,data)=>{if(id===projectId){setDetail((current)=>current?{...current,...data}:current);await saveProductionJob(uid,id,data);}});await refreshPending();await load();}
 async function act(action:string,payload:Record<string,unknown>={},lifecycle=false){if(!detail)return;setBusy(action);setError("");try{const uid=auth.currentUser?.uid;if(!uid)throw new Error("Owner identity is not available.");if(!navigator.onLine){await queueProductionMutation(uid,projectId,action,payload,detail.operationsVersion+pending,pending===0?detail.updatedAt:undefined);setPending(x=>x+1);setOffline(true);return;}const t=await token();const response=await fetch(`/api/admin/purepress/jobs/${encodeURIComponent(projectId)}/production`,{method:"POST",headers:{"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})},credentials:"include",cache:"no-store",body:JSON.stringify({action,...payload,clientMutationId:secureMutationId(),baseVersion:detail.operationsVersion,expectedUpdatedAt:detail.updatedAt})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Production update was rejected.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Production update was rejected.");}finally{setBusy("");}}
 if(!detail)return <section className={styles.panel}><h2>Production</h2><p className={styles.error}>{error||"Opening production operations…"}</p></section>;
 const p=detail.productionPlan||{},r=detail.readiness||{};
 return <section className={styles.panel} aria-labelledby="pp-production-heading">
  <div className={styles.heading}><div><p className="pp-kicker">PRODUCTION FLOOR</p><h2 id="pp-production-heading">Garments → machine → QC</h2><p>Record what is physically true in the Studio. Lifecycle changes remain server-authoritative.</p></div><div className={styles.sync}>{offline?<strong>OFFLINE — SHOWING SAVED PUREPRESS DATA</strong>:<strong>SYNCED</strong>}<span>{saved?"SAVED ON THIS DEVICE":"NETWORK ONLY"}</span>{pending>0&&<span>{pending} UPDATE(S) WAITING TO SYNC</span>}<button type="button" onClick={()=>void syncNow()} disabled={offline}>SYNC NOW</button></div></div>
  {error&&<p className={styles.error} role="alert">{error}</p>}
  <div className={styles.snapshot}><Fact label="Stage" value={friendly(detail.status)}/><Fact label="Garments" value={friendly(r.items)}/><Fact label="Machine" value={p.machineAssignment||"Not assigned"}/><Fact label="Progress" value={`${p.completedQuantity??0} / ${p.targetQuantity??detail.quantity??"—"}`}/><Fact label="Rejected" value={String(p.rejectedQuantity??0)}/><Fact label="Quality" value={friendly(r.qc)}/><Fact label="Next action" value={detail.nextAction?.action||"Not set"}/></div>
  <div className={styles.columns}><ReceivingForm rows={detail.receiving} busy={busy} onSave={(v)=>act("update_receiving",v)}/><PlanForm plan={p} quantity={detail.quantity} busy={busy} onSave={(v)=>act("update_plan",v)}/></div>
  <div className={styles.actions}><button onClick={()=>void act("start",{},true)} disabled={Boolean(busy)||detail.status!=="approved_for_production"}>START PRODUCTION</button><button onClick={()=>void act("pause",{},true)} disabled={Boolean(busy)||r.production!=="running"}>PAUSE</button><button onClick={()=>void act("resume",{},true)} disabled={Boolean(busy)||r.production!=="paused"}>RESUME</button><button onClick={()=>void act("finish",{},true)} disabled={Boolean(busy)||detail.status!=="in_production"}>FINISH PRODUCTION</button></div>
  {detail.status==="in_production"&&<ProgressForm plan={p} busy={busy} onSave={(v)=>act("progress",v)}/>} 
  {detail.status==="quality_check"&&<QcForm checks={detail.qualityChecks} busy={busy} onSave={(v)=>act("update_qc",v)} onPass={()=>act("pass_qc",{},true)}/>} 
  {detail.status==="ready"&&<CompletionForm busy={busy} onComplete={(note)=>act("complete",{note},true)}/>} 
  <NextActionForm value={detail.nextAction?.action||""} busy={busy} onSave={(nextAction,blocker)=>act("update_next_action",{nextAction,blocker})}/>
  {pending>0&&<p className={styles.pending}>Saved offline actions are waiting to sync. The stage shown above remains the last authoritative saved stage until the server accepts them.</p>}
  <details><summary>Production history</summary><ul className={styles.history}>{detail.history?.map(x=><li key={x.id}><strong>{friendly(x.type)}</strong><span>{new Date(x.createdAt).toLocaleString()}</span><p>{x.note||"Recorded operational update"}</p></li>)}</ul></details>
 </section>;
}
function Fact({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function ReceivingForm({rows,busy,onSave}:{rows:any[];busy:string;onSave:(v:any)=>Promise<void>}){const row=rows?.[0]||{};async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await onSave({receivingId:"primary",itemSpecification:String(f.get("itemSpecification")||"Job garments/items"),expectedQuantity:Number(f.get("expectedQuantity")||0),receivedQuantity:Number(f.get("receivedQuantity")||0),shortageQuantity:Number(f.get("shortageQuantity")||0),extraQuantity:Number(f.get("extraQuantity")||0),condition:String(f.get("condition")||"good"),procurementOrdered:f.get("procurementOrdered")!==null,issueNotes:String(f.get("issueNotes")||""),resolveIssue:!String(f.get("issueNotes")||"")});}return <form className={styles.form} onSubmit={submit}><h3>GARMENTS / RECEIVING</h3><label>Items<input name="itemSpecification" defaultValue={row.itemSpecification||"Job garments/items"} maxLength={220}/></label><div className={styles.mini}><label>Expected<input name="expectedQuantity" type="number" min="0" defaultValue={row.quantityExpected??row.quantityRequired??0}/></label><label>Received<input name="receivedQuantity" type="number" min="0" defaultValue={row.quantityReceived??0}/></label><label>Shortage<input name="shortageQuantity" type="number" min="0" defaultValue={row.shortage??0}/></label><label>Extras<input name="extraQuantity" type="number" min="0" defaultValue={row.extras??0}/></label></div><label><input name="procurementOrdered" type="checkbox" value="yes"/> Procurement ordered</label><label>Condition<select name="condition" defaultValue={row.condition||"good"}><option value="good">Good</option><option value="mixed">Mixed</option><option value="damaged">Damaged</option><option value="issue">Issue</option></select></label><label>Issue note<textarea name="issueNotes" rows={3} maxLength={600} defaultValue={row.issueNotes||""}/></label><button disabled={Boolean(busy)}>SAVE RECEIVING</button></form>}
function PlanForm({plan,quantity,busy,onSave}:{plan:any;quantity:number|null;busy:string;onSave:(v:any)=>Promise<void>}){async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await onSave({machineAssignment:String(f.get("machineAssignment")||""),operatorName:String(f.get("operatorName")||""),targetQuantity:Number(f.get("targetQuantity")||0),scheduledStartAt:String(f.get("scheduledStartAt")||""),scheduledDueAt:String(f.get("scheduledDueAt")||""),productionNotes:String(f.get("productionNotes")||"")});}return <form className={styles.form} onSubmit={submit}><h3>PRODUCTION PLAN</h3><label>Machine<input name="machineAssignment" maxLength={120} defaultValue={plan.machineAssignment||""} placeholder="e.g. 6-head embroidery machine"/></label><label>Operator<input name="operatorName" maxLength={120} defaultValue={plan.operatorName||""}/></label><label>Target quantity<input name="targetQuantity" type="number" min="1" max="1000000" defaultValue={plan.targetQuantity??quantity??1}/></label><div className={styles.mini}><label>Start<input name="scheduledStartAt" type="datetime-local" defaultValue={plan.scheduledStartAt?.slice(0,16)||""}/></label><label>Due<input name="scheduledDueAt" type="datetime-local" defaultValue={plan.scheduledDueAt?.slice(0,16)||""}/></label></div><label>Production notes<textarea name="productionNotes" rows={3} maxLength={1600} defaultValue={plan.productionNotes||""}/></label><button disabled={Boolean(busy)}>SAVE PRODUCTION PLAN</button></form>}
function ProgressForm({plan,busy,onSave}:{plan:any;busy:string;onSave:(v:any)=>Promise<void>}){async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await onSave({completedQuantity:Number(f.get("completedQuantity")||0),rejectedQuantity:Number(f.get("rejectedQuantity")||0),reworkQuantity:Number(f.get("reworkQuantity")||0),note:String(f.get("note")||"")});}return <form className={styles.progress} onSubmit={submit}><h3>PROGRESS</h3><label>Completed<input name="completedQuantity" type="number" min="0" max={plan.targetQuantity??1000000} defaultValue={plan.completedQuantity??0}/></label><label>Rejected<input name="rejectedQuantity" type="number" min="0" defaultValue={plan.rejectedQuantity??0}/></label><label>Rework<input name="reworkQuantity" type="number" min="0" defaultValue={plan.reworkQuantity??0}/></label><label>Note<input name="note" maxLength={1000}/></label><button disabled={Boolean(busy)}>RECORD PROGRESS</button></form>}
function QcForm({checks,busy,onSave,onPass}:{checks:any[];busy:string;onSave:(v:any)=>Promise<void>;onPass:()=>Promise<void>}){return <div className={styles.qc}><h3>QUALITY CHECK</h3>{checks.map(c=><div key={c.key}><strong>{c.label}</strong><select value={c.state} onChange={e=>void onSave({key:c.key,state:e.target.value,issueNote:c.issueNote||""})}><option value="not_checked">Not checked</option><option value="passed">Passed</option><option value="issue">Issue</option><option value="not_applicable">Not applicable</option></select>{c.state==="issue"&&<input aria-label={`${c.label} issue note`} defaultValue={c.issueNote||""} onBlur={e=>void onSave({key:c.key,state:"issue",issueNote:e.currentTarget.value})} maxLength={600} placeholder="What needs fixing?"/>}</div>)}<button onClick={()=>void onPass()} disabled={Boolean(busy)}>PASS FINAL QC — READY</button></div>}
function CompletionForm({busy,onComplete}:{busy:string;onComplete:(note:string)=>Promise<void>}){const [note,setNote]=useState("");return <div className={styles.completion}><h3>CUSTOMER HANDOFF</h3><input value={note} onChange={e=>setNote(e.target.value)} maxLength={1000} placeholder="Optional completion note"/><button onClick={()=>void onComplete(note)} disabled={Boolean(busy)}>MARK COMPLETED</button></div>}
function NextActionForm({value,busy,onSave}:{value:string;busy:string;onSave:(a:string,b:string)=>Promise<void>}){const [a,setA]=useState(value),[b,setB]=useState("");return <div className={styles.next}><h3>NEXT ACTION</h3><input value={a} onChange={e=>setA(e.target.value)} maxLength={240}/><input value={b} onChange={e=>setB(e.target.value)} maxLength={300} placeholder="Optional blocker"/><button onClick={()=>void onSave(a,b)} disabled={Boolean(busy)||!a.trim()}>SAVE NEXT ACTION</button></div>}
