"use client";
import { type FormEvent, useCallback, useEffect, useState } from "react";
import styles from "./PurePressProofApproval.module.css";
interface ProofFile { id:string; fileName:string; mimeType:string; sizeBytes:number; viewUrl:string; }
interface ProofDecision { type:"approved"|"changes_requested"; source:"secure_link"|"owner_recorded"; approverName:string; comment?:string; decidedAt:string; }
interface ProofView { reference:string; customerName?:string; organisation?:string; revision:number; status:"awaiting_customer"|"approved"|"changes_requested"; proofFiles:ProofFile[]; customerVisibleNotes?:string; placementSummary?:string; designWidthMm?:number; designHeightMm?:number; threadColorSummary?:string; issuedAt?:string; decision?:ProofDecision; }
export default function PurePressProofApproval({token}:{token:string}){
 const[proof,setProof]=useState<ProofView|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/purepress/proof/${encodeURIComponent(token)}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"This proof could not be opened.");setProof(data.proof);}catch(reason){setError(reason instanceof Error?reason.message:"This proof could not be opened.");}finally{setLoading(false);}},[token]);
 useEffect(()=>{void load();},[load]);
 async function decide(event:FormEvent<HTMLFormElement>,decision:"approve"|"request_changes"){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(decision);setError("");try{const response=await fetch(`/api/purepress/proof/${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/json"},cache:"no-store",body:JSON.stringify({decision,approverName:String(form.get("approverName")||""),comment:String(form.get("comment")||"")})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Your proof decision could not be recorded.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Your proof decision could not be recorded.");}finally{setBusy("");}}
 if(loading)return <main className={styles.page}><div className={styles.card}><p>Opening your PurePress artwork proof…</p></div></main>;
 if(error&&!proof)return <main className={styles.page}><div className={styles.card}><Brand/><p className={styles.error}>{error}</p></div></main>;if(!proof)return null;const decided=proof.status!=="awaiting_customer";
 return <main className={styles.page}><div className={styles.card}><Brand/><header className={styles.header}><p className={styles.kicker}>ARTWORK PROOF</p><h1>Revision {proof.revision}</h1><p>{proof.reference}{proof.customerName?` · ${proof.customerName}`:""}{proof.organisation?` · ${proof.organisation}`:""}</p></header>{error&&<p className={styles.error} role="alert">{error}</p>}<p className={styles.notice}>Please review this proof carefully. Approval applies to this exact proof revision.</p><section className={styles.proofs} aria-label="Proof files">{proof.proofFiles.map((file)=><ProofFileCard key={file.id} file={file}/>)}</section><section className={styles.facts}>{proof.placementSummary&&<Fact label="Placement" value={proof.placementSummary}/>} {(proof.designWidthMm||proof.designHeightMm)&&<Fact label="Design size" value={`${proof.designWidthMm??"—"} × ${proof.designHeightMm??"—"} mm`}/>} {proof.threadColorSummary&&<Fact label="Thread colours" value={proof.threadColorSummary}/>} {proof.customerVisibleNotes&&<Fact label="Notes from PurePress" value={proof.customerVisibleNotes}/>}</section>{decided&&proof.decision?<section className={styles.decision}><h2>{proof.decision.type==="approved"?"Proof approved":"Changes requested"}</h2><p>Recorded for {proof.decision.approverName} on {new Date(proof.decision.decidedAt).toLocaleString()}.</p>{proof.decision.comment&&<p>{proof.decision.comment}</p>}</section>:<div className={styles.actionsGrid}><form onSubmit={(event)=>void decide(event,"approve")} className={styles.actionCard}><h2>Approve this proof</h2><label>CUSTOMER / APPROVER NAME<input name="approverName" required maxLength={120}/></label><label>Optional comment<textarea name="comment" maxLength={1200} rows={3}/></label><p>You are approving revision R{proof.revision} as shown.</p><button type="submit" disabled={Boolean(busy)}>{busy==="approve"?"APPROVING…":"APPROVE PROOF"}</button></form><form onSubmit={(event)=>void decide(event,"request_changes")} className={styles.actionCard}><h2>Request changes</h2><label>CUSTOMER / APPROVER NAME<input name="approverName" required maxLength={120}/></label><label>Tell PurePress what you would like changed in this proof.<textarea name="comment" required maxLength={1200} rows={5}/></label><button type="submit" className={styles.secondary} disabled={Boolean(busy)}>{busy==="request_changes"?"SENDING…":"REQUEST CHANGES"}</button></form></div>}</div></main>;
}
function Brand(){return <div className={styles.brand}><strong>PUREPRESS</strong><span>Custom embroidery</span></div>;}function Fact({label,value}:{label:string;value:string}){return <div><strong>{label}</strong><p>{value}</p></div>;}function ProofFileCard({file}:{file:ProofFile}){const image=file.mimeType.startsWith("image/");return <article className={styles.fileCard}>{image?<img src={file.viewUrl} alt={`Artwork proof: ${file.fileName}`}/>:<div className={styles.document}>PROOF DOCUMENT</div>}<div><strong>{file.fileName}</strong><a href={file.viewUrl} target="_blank" rel="noreferrer">OPEN PROOF FILE</a></div></article>;}
