"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { auth } from "@/utils/firebaseConfig";
import { clearPurePressPrivateOfflineData } from "@/lib/purepress/offline/db";
import { getSavedProductionDesk, isPurePressTrustedDevice, listProductionOutbox, saveProductionDesk, setPurePressTrustedDevice, syncProductionOutbox } from "@/lib/purepress/offline/production";
import styles from "./PurePressProductionDesk.module.css";
type Row={projectId:string;referenceCode:string;customer:string;organisation:string|null;itemSummary:string;quantity:number|null;requestedDate:string|null;timingFlexible:boolean;supplySource:string;status:string;itemsReadiness:string;artworkReadiness:string;proofReadiness:string;productionReadiness:string;qcReadiness:string;machineAssignment:string|null;targetQuantity:number|null;completedQuantity:number;rejectedQuantity:number;receivingExpected:number;receivingReceived:number;blocker:string|null;nextAction:any;operationsVersion:number;updatedAt:string};
type View="attention"|"waiting"|"readyprod"|"scheduled"|"production"|"qc"|"ready"|"all";
const friendly=(v?:string)=>v?v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase()):"—";
async function token(){return auth.currentUser?.getIdToken();}
export default function PurePressProductionDesk(){const [jobs,setJobs]=useState<Row[]>([]),[view,setView]=useState<View>("attention"),[error,setError]=useState(""),[offline,setOffline]=useState(false),[lastSync,setLastSync]=useState(""),[uid,setUid]=useState(""),[trusted,setTrusted]=useState(false),[pending,setPending]=useState(0);
 const refreshPending=useCallback(async(id:string)=>{if(id)setPending((await listProductionOutbox(id)).length);},[]);
 const load=useCallback(async()=>{const id=auth.currentUser?.uid||uid;if(!id)return;setError("");try{const t=await token();const response=await fetch("/api/admin/purepress/production-desk",{headers:t?{Authorization:`Bearer ${t}`}:{},credentials:"include",cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not load the production desk.");const stamp=new Date().toISOString();setJobs(data.jobs||[]);setOffline(false);setLastSync(stamp);if(await isPurePressTrustedDevice(id))await saveProductionDesk(id,data.jobs||[],stamp);}catch(reason){const cached=await getSavedProductionDesk<Row>(id);if(cached){setJobs(cached.jobs);setLastSync(cached.lastSyncedAt);setOffline(true);}else setError(reason instanceof Error?reason.message:"Production desk unavailable.");}await refreshPending(id);},[uid,refreshPending]);
 useEffect(()=>auth.onAuthStateChanged(async user=>{const id=user?.uid||"";setUid(id);if(!id){setTrusted(false);return;}setTrusted(await isPurePressTrustedDevice(id));await load();}),[load]);
 useEffect(()=>{const online=()=>{setOffline(false);void syncNow();};const off=()=>setOffline(true);const focus=()=>{if(navigator.onLine)void syncNow();};window.addEventListener("online",online);window.addEventListener("offline",off);window.addEventListener("focus",focus);return()=>{window.removeEventListener("online",online);window.removeEventListener("offline",off);window.removeEventListener("focus",focus);};});
 async function syncNow(){if(!uid||!navigator.onLine)return;await syncProductionOutbox(uid,token);await load();}
 async function toggleTrusted(){if(!uid)return;const next=!trusted;await setPurePressTrustedDevice(uid,next);setTrusted(next);if(next){await saveProductionDesk(uid,jobs,lastSync||new Date().toISOString());}else await clearPurePressPrivateOfflineData(uid);await refreshPending(uid);}
 const groups=useMemo(()=>({attention:jobs.filter(j=>Boolean(j.blocker)||j.itemsReadiness==="issue"||j.qcReadiness==="issue"),waiting:jobs.filter(j=>["needs_information","awaiting_quote_approval","awaiting_proof_approval"].includes(j.status)),readyprod:jobs.filter(j=>j.status==="approved_for_production"&&!['scheduled'].includes(j.productionReadiness)),scheduled:jobs.filter(j=>j.status==="approved_for_production"&&j.productionReadiness==="scheduled"),production:jobs.filter(j=>j.status==="in_production"),qc:jobs.filter(j=>j.status==="quality_check"),ready:jobs.filter(j=>j.status==="ready"),all:jobs}),[jobs]); const visible=groups[view];
 return <section className={styles.desk} aria-labelledby="production-desk-heading"><div className={styles.head}><div><p className="pp-kicker">PRODUCTION FLOOR</p><h1 id="production-desk-heading">Studio production desk</h1><p>Garments, machine work, progress, quality and the next action in one workshop view.</p></div><div className={styles.offlineBox}>{offline?<strong>OFFLINE — SHOWING SAVED PUREPRESS DATA</strong>:<strong>LIVE PUREPRESS DATA</strong>}<span>{lastSync?`LAST SYNCED ${new Date(lastSync).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`:"NOT SYNCED YET"}</span><button onClick={()=>void toggleTrusted()} disabled={!uid}>{trusted?"REMOVE OFFLINE DATA FROM THIS DEVICE":"KEEP ACTIVE JOBS ON THIS DEVICE"}</button>{trusted&&<small>This trusted device retains private job metadata under your owner account. Files are not stored.</small>}{pending>0&&<button onClick={()=>void syncNow()} disabled={offline}>{pending} SAVED UPDATE(S) — SYNC NOW</button>}</div></div>
 {error&&<p className={styles.error}>{error}</p>}<div className={styles.tabs}>{([['attention','ATTENTION'],['waiting','WAITING'],['readyprod','READY FOR PRODUCTION'],['scheduled','SCHEDULED'],['production','IN PRODUCTION'],['qc','QC'],['ready','READY'],['all','ALL ACTIVE']] as [View,string][]).map(([k,l])=><button key={k} className={view===k?styles.active:""} onClick={()=>setView(k)}>{l}<b>{groups[k].length}</b></button>)}</div>
 <div className={styles.rows}>{visible.map(job=><article key={job.projectId}><div><span className={styles.ref}>{job.referenceCode}</span><h2>{job.customer}{job.organisation?` · ${job.organisation}`:""}</h2><p>{job.itemSummary} · {job.quantity??"—"} item(s)</p></div><div><span>GARMENTS</span><strong>{job.receivingReceived}{job.receivingExpected?` / ${job.receivingExpected}`:""} · {friendly(job.itemsReadiness)}</strong><small>{friendly(job.supplySource)}</small></div><div><span>MACHINE / PROGRESS</span><strong>{job.machineAssignment||"Not assigned"}</strong><small>{job.completedQuantity} / {job.targetQuantity??job.quantity??"—"} · {job.rejectedQuantity} rejected</small></div><div><span>STAGE</span><strong>{friendly(job.status)}</strong><small>{friendly(job.productionReadiness)} · QC {friendly(job.qcReadiness)}</small></div><div className={styles.next}><span>NEXT ACTION</span><strong>{job.nextAction?.action||"Review job"}</strong>{job.blocker&&<small>BLOCKER: {job.blocker}</small>}</div><Link href={`/admin/purepress/jobs/${encodeURIComponent(job.projectId)}`}>OPEN JOB</Link></article>)}</div>
 {!visible.length&&!error&&<p className={styles.empty}>No active jobs match this view.</p>}</section>}
